name: scrutiny_domain
description: Common data entites and business logics for Scrutiny
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.1

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  scrutiny_core:
    path: ../core

dev_dependencies:
  build_runner: ^2.15.1
  freezed: ^3.2.5
  lints: ^6.0.0
  test: ^1.25.6
